CREATE DATABASE smooth-pdv;

USE smooth-pdv;

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: tipo_usuario; Type: TYPE; Schema: public; Owner: thejohnjohn
--

CREATE TYPE public.tipo_usuario AS ENUM (
    'ADMIN',
    'GERENTE',
    'VENDEDOR'
);


ALTER TYPE public.tipo_usuario OWNER TO thejohnjohn;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: compra; Type: TABLE; Schema: public; Owner: thejohnjohn
--

CREATE TABLE public.compra (
    id integer NOT NULL,
    data date NOT NULL,
    id_loja integer DEFAULT 1 NOT NULL,
    id_vendedor integer
);


ALTER TABLE public.compra OWNER TO thejohnjohn;

--
-- Name: compra_id_seq; Type: SEQUENCE; Schema: public; Owner: thejohnjohn
--

ALTER TABLE public.compra ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compra_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: item_mercadoria; Type: TABLE; Schema: public; Owner: thejohnjohn
--

CREATE TABLE public.item_mercadoria (
    id integer NOT NULL,
    quantidade integer NOT NULL,
    idmercadoria integer NOT NULL,
    idcompra integer NOT NULL
);


ALTER TABLE public.item_mercadoria OWNER TO thejohnjohn;

--
-- Name: item_mercadoria_id_seq; Type: SEQUENCE; Schema: public; Owner: thejohnjohn
--

ALTER TABLE public.item_mercadoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.item_mercadoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: loja; Type: TABLE; Schema: public; Owner: thejohnjohn
--

CREATE TABLE public.loja (
    id integer NOT NULL,
    nome character varying(100) NOT NULL,
    cnpj character varying(14),
    endereco text,
    telefone character varying(20),
    email character varying(150),
    ativo boolean DEFAULT true,
    criado_em timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.loja OWNER TO thejohnjohn;

--
-- Name: loja_id_seq; Type: SEQUENCE; Schema: public; Owner: thejohnjohn
--

ALTER TABLE public.loja ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.loja_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mercadoria; Type: TABLE; Schema: public; Owner: thejohnjohn
--

CREATE TABLE public.mercadoria (
    id integer NOT NULL,
    descricao character varying(100) NOT NULL,
    preco numeric(10,2) NOT NULL,
    id_usuario integer,
    id_loja integer DEFAULT 1 NOT NULL
);


ALTER TABLE public.mercadoria OWNER TO thejohnjohn;

--
-- Name: pagamento; Type: TABLE; Schema: public; Owner: thejohnjohn
--

CREATE TABLE public.pagamento (
    id integer NOT NULL,
    data date NOT NULL,
    valor numeric(10,2) NOT NULL,
    idcompra integer NOT NULL,
    metodo_pagamento character varying(50) DEFAULT 'DINHEIRO'::character varying NOT NULL,
    status character varying(20) DEFAULT 'APROVADO'::character varying NOT NULL,
    troco numeric(10,2) DEFAULT 0,
    observacao text
);


ALTER TABLE public.pagamento OWNER TO thejohnjohn;

--
-- Name: pagamento_id_seq; Type: SEQUENCE; Schema: public; Owner: thejohnjohn
--

ALTER TABLE public.pagamento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pagamento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario; Type: TABLE; Schema: public; Owner: thejohnjohn
--

CREATE TABLE public.usuario (
    id integer NOT NULL,
    nome character varying(100) NOT NULL,
    email character varying(150) NOT NULL,
    senha character varying(255) NOT NULL,
    tipo public.tipo_usuario NOT NULL,
    criado_em timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    id_loja integer DEFAULT 1 NOT NULL
);


ALTER TABLE public.usuario OWNER TO thejohnjohn;

--
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: thejohnjohn
--

ALTER TABLE public.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: compra compra_pkey; Type: CONSTRAINT; Schema: public; Owner: thejohnjohn
--

ALTER TABLE ONLY public.compra
    ADD CONSTRAINT compra_pkey PRIMARY KEY (id);


--
-- Name: item_mercadoria item_mercadoria_pkey; Type: CONSTRAINT; Schema: public; Owner: thejohnjohn
--

ALTER TABLE ONLY public.item_mercadoria
    ADD CONSTRAINT item_mercadoria_pkey PRIMARY KEY (id, idmercadoria, idcompra);


--
-- Name: loja loja_cnpj_key; Type: CONSTRAINT; Schema: public; Owner: thejohnjohn
--

ALTER TABLE ONLY public.loja
    ADD CONSTRAINT loja_cnpj_key UNIQUE (cnpj);


--
-- Name: loja loja_pkey; Type: CONSTRAINT; Schema: public; Owner: thejohnjohn
--

ALTER TABLE ONLY public.loja
    ADD CONSTRAINT loja_pkey PRIMARY KEY (id);


--
-- Name: mercadoria mercadoria_pkey; Type: CONSTRAINT; Schema: public; Owner: thejohnjohn
--

ALTER TABLE ONLY public.mercadoria
    ADD CONSTRAINT mercadoria_pkey PRIMARY KEY (id);


--
-- Name: pagamento pagamento_pkey; Type: CONSTRAINT; Schema: public; Owner: thejohnjohn
--

ALTER TABLE ONLY public.pagamento
    ADD CONSTRAINT pagamento_pkey PRIMARY KEY (id, idcompra);


--
-- Name: usuario usuario_email_key; Type: CONSTRAINT; Schema: public; Owner: thejohnjohn
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_email_key UNIQUE (email);


--
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: thejohnjohn
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);


--
-- Name: fk_item_mercadoria_compra1_idx; Type: INDEX; Schema: public; Owner: thejohnjohn
--

CREATE INDEX fk_item_mercadoria_compra1_idx ON public.item_mercadoria USING btree (idcompra);


--
-- Name: fk_item_mercadoria_mercadoria_idx; Type: INDEX; Schema: public; Owner: thejohnjohn
--

CREATE INDEX fk_item_mercadoria_mercadoria_idx ON public.item_mercadoria USING btree (idmercadoria);


--
-- Name: fk_pagamento_compra1_idx; Type: INDEX; Schema: public; Owner: thejohnjohn
--

CREATE INDEX fk_pagamento_compra1_idx ON public.pagamento USING btree (idcompra);


--
-- Name: idx_compra_loja; Type: INDEX; Schema: public; Owner: thejohnjohn
--

CREATE INDEX idx_compra_loja ON public.compra USING btree (id_loja);


--
-- Name: idx_compra_vendedor; Type: INDEX; Schema: public; Owner: thejohnjohn
--

CREATE INDEX idx_compra_vendedor ON public.compra USING btree (id_vendedor);


--
-- Name: idx_mercadoria_loja; Type: INDEX; Schema: public; Owner: thejohnjohn
--

CREATE INDEX idx_mercadoria_loja ON public.mercadoria USING btree (id_loja);


--
-- Name: idx_usuario_loja; Type: INDEX; Schema: public; Owner: thejohnjohn
--

CREATE INDEX idx_usuario_loja ON public.usuario USING btree (id_loja);


--
-- Name: compra fk_compra_loja; Type: FK CONSTRAINT; Schema: public; Owner: thejohnjohn
--

ALTER TABLE ONLY public.compra
    ADD CONSTRAINT fk_compra_loja FOREIGN KEY (id_loja) REFERENCES public.loja(id);


--
-- Name: compra fk_compra_vendedor; Type: FK CONSTRAINT; Schema: public; Owner: thejohnjohn
--

ALTER TABLE ONLY public.compra
    ADD CONSTRAINT fk_compra_vendedor FOREIGN KEY (id_vendedor) REFERENCES public.usuario(id);


--
-- Name: item_mercadoria fk_item_mercadoria_compra1; Type: FK CONSTRAINT; Schema: public; Owner: thejohnjohn
--

ALTER TABLE ONLY public.item_mercadoria
    ADD CONSTRAINT fk_item_mercadoria_compra1 FOREIGN KEY (idcompra) REFERENCES public.compra(id);


--
-- Name: item_mercadoria fk_item_mercadoria_mercadoria; Type: FK CONSTRAINT; Schema: public; Owner: thejohnjohn
--

ALTER TABLE ONLY public.item_mercadoria
    ADD CONSTRAINT fk_item_mercadoria_mercadoria FOREIGN KEY (idmercadoria) REFERENCES public.mercadoria(id);


--
-- Name: mercadoria fk_mercadoria_loja; Type: FK CONSTRAINT; Schema: public; Owner: thejohnjohn
--

ALTER TABLE ONLY public.mercadoria
    ADD CONSTRAINT fk_mercadoria_loja FOREIGN KEY (id_loja) REFERENCES public.loja(id);


--
-- Name: mercadoria fk_mercadoria_usuario; Type: FK CONSTRAINT; Schema: public; Owner: thejohnjohn
--

ALTER TABLE ONLY public.mercadoria
    ADD CONSTRAINT fk_mercadoria_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuario(id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: pagamento fk_pagamento_compra1; Type: FK CONSTRAINT; Schema: public; Owner: thejohnjohn
--

ALTER TABLE ONLY public.pagamento
    ADD CONSTRAINT fk_pagamento_compra1 FOREIGN KEY (idcompra) REFERENCES public.compra(id);


--
-- Name: usuario fk_usuario_loja; Type: FK CONSTRAINT; Schema: public; Owner: thejohnjohn
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT fk_usuario_loja FOREIGN KEY (id_loja) REFERENCES public.loja(id);


--
-- PostgreSQL database dump complete
--

