CREATE TYPE "tipo_usuario" AS ENUM (
  'ADMIN',
  'GERENTE',
  'VENDEDOR',
  'CLIENTE'
);

CREATE TABLE "usuario" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nome" varchar(100) NOT NULL,
  "email" varchar(150) UNIQUE NOT NULL,
  "senha" varchar(255) NOT NULL,
  "tipo" tipo_usuario NOT NULL,
  "criado_em" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "mercadoria" (
  "id" int PRIMARY KEY NOT NULL,
  "descricao" varchar(100) NOT NULL,
  "preco" decimal(10,2) NOT NULL,
  "id_usuario" int
);

CREATE TABLE "compra" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "data" date NOT NULL,
  "id_cliente" int
);

CREATE TABLE "item_mercadoria" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "quantidade" int NOT NULL,
  "idmercadoria" int NOT NULL,
  "idcompra" int NOT NULL,
  PRIMARY KEY ("id", "idmercadoria", "idcompra")
);

CREATE TABLE "pagamento" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "data" date NOT NULL,
  "valor" decimal(10,2) NOT NULL,
  "idcompra" int NOT NULL,
  PRIMARY KEY ("id", "idcompra")
);

CREATE INDEX "fk_item_mercadoria_mercadoria_idx" ON "item_mercadoria" ("idmercadoria");
CREATE INDEX "fk_item_mercadoria_compra1_idx" ON "item_mercadoria" ("idcompra");
CREATE INDEX "fk_pagamento_compra1_idx" ON "pagamento" ("idcompra");

ALTER TABLE "item_mercadoria" 
  ADD CONSTRAINT "fk_item_mercadoria_mercadoria" 
  FOREIGN KEY ("idmercadoria") REFERENCES "mercadoria" ("id") 
  ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "item_mercadoria" 
  ADD CONSTRAINT "fk_item_mercadoria_compra1" 
  FOREIGN KEY ("idcompra") REFERENCES "compra" ("id") 
  ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "pagamento" 
  ADD CONSTRAINT "fk_pagamento_compra1" 
  FOREIGN KEY ("idcompra") REFERENCES "compra" ("id") 
  ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "mercadoria" 
  ADD CONSTRAINT "fk_mercadoria_usuario" 
  FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id") 
  ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "compra" 
  ADD CONSTRAINT "fk_compra_cliente" 
  FOREIGN KEY ("id_cliente") REFERENCES "usuario" ("id") 
  ON DELETE SET NULL ON UPDATE CASCADE;

-- Adicionar colunas de pagamento
ALTER TABLE pagamento 
ADD COLUMN metodo_pagamento VARCHAR(50) NOT NULL DEFAULT 'DINHEIRO',
ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'APROVADO',
ADD COLUMN troco DECIMAL(10,2) DEFAULT 0,
ADD COLUMN observacao TEXT;